### PR TITLE
Final clean-up

### PR DESCRIPTION
**Pull request by davidlmobley**
This attempts final clean-up:
- Clarifies grid issue noted in #69 (thereby also closing #52)
- Fixes minor typos
- Improves figure captions
- Adjusts version number
- Makes sure every figure referenced in text
- Makes version number 1.0
- Fixes a broken reference
- Improves a line break

### CODE REVIEW

**Comment by davidlmobley** [comment]
@hmayes or @samarjeet do a quick check? Offline now for an hour or so, will likely submit at 8 or 9 am Pacific.

Probably this supersedes #77 unless Samarjeet wants to propose different edits to the bullet point in question.

**Comment by hmayes** [comment]
What should I focus on for the quick check? Anything new?

**Comment by davidlmobley** [comment]
@hmayes - just scan the diff (click the "files changed" tab, top right) and make sure the changes look OK to you. :)

**Comment by justinGilmer** [comment]
@davidlmobley working through the document now. Found a few typos and some word choices that i am changing now. Ill submit as a separate PR and when this one is merged, we can go through my changes. Information wise, it all seems fine to me.

**Comment by hmayes** [comment]
Great. Looks like there are only a couple flags of things we really want to
fix before submission.

I think it would be nice to have a list of all the abbreviations/symbols.
If this is something we want to do, I'd hold off until revision time (and
add a issue tracker).

**Comment by samarjeet** [comment]
Page 2 has a single line paragraph. Should we try to absorb that line in
another paragraph or is it ok?

**Comment by EfremBraun** [comment]
The reference to Ewald_1921 is broken, but I'm not sure why. Can somebody fix it?

**Comment by samarjeet** [comment]
It seems to be fine in the "mobley" branch that I am on right now. Can you
please check that, I think @David Mobley <dmobley@uci.edu> will merge this
one to master soon ?

**Comment by EfremBraun** [comment]
Yep you're right, it's fine here.

**Comment by davidlmobley** [comment]
@hmayes 
> I think it would be nice to have a list of all the abbreviations/symbols.
If this is something we want to do, I'd hold off until revision time (and
add a issue tracker).

Good idea. I'll put this into the issue on things to do for revision.

@samarjeet I'll check out the single-sentence paragraph. Sometimes these are OK.

I'll merge this.

**Comment by davidlmobley** [comment]
That single sentence paragraph looks OK to me. A paragraph is basically a logical unit that expresses a thought; in this case the sentence stands alone and doesn't belong in either of the surrounding paragraphs, so I think it's best as is.

**Pull request merged**
