### PR TITLE
Added entry for Bussi Thermostat in table

### PR DESCRIPTION
**Pull request by justinGilmer**
Responding to @EfremBraun's comment to add an entry for the Bussi Thermostat in the thermostat summary table.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Can you also change "Hoover" to "Gaussian" in this?

**Comment by EfremBraun** [comment]
Also would you mind sending me the figure so I could make other edits in line with the pull request I'm preparing?

**Comment by justinGilmer** [comment]
Its included in this PR.

Should have it once you merge these changes

**Comment by davidlmobley** [comment]
This is merged, @justinGilmer .

**Pull request merged**
