### PR TITLE
Revisions to thermodynamics and barostats

### PR DESCRIPTION
**Pull request by EfremBraun**

### CODE REVIEW

**Comment by davidlmobley** [comment]
"WIP" noted. :)

**Comment by EfremBraun** [comment]
I think it's ready now.

**Comment by EfremBraun** [comment]
Since this fixes most of what's mentioned in Issue #67, I'm going to close that issue and start a new one with the ones that haven't been fixed.

**Comment by EfremBraun** [comment]
Er, give me another second to make a few other minor changes.

**Comment by EfremBraun** [comment]
Other changes are done. Feel free to merge.

**Pull request merged**
