### PR TITLE
Edit long-range electrostatics section

### PR DESCRIPTION
**Pull request by davidlmobley**
I started editing this section, which needs lots of help, but didn't get all the way through it. I'll be offline until around 8-ish (Pacific) so if you'd like to carry on where I left off in the meantime, please have at it.  You can commit directly to this branch if you like, or if you're less certain about what you're doing you can do a PR to this branch. :) 

Tagging @EfremBraun and @JIMonroe in case you have time.

There are a couple major things I'm doing so far as I go through it:
- Reducing the number of equations (most don't seem to add much value)
- Making it less technical
- Improving grammar, etc.

### CODE REVIEW

**Comment by EfremBraun** [comment]
Sorry, don't think I'll be able to get to this one tonight.

**Comment by JIMonroe** [comment]
I have one more PR coming with some minor things, but if I get to this it won't be for another two hours or so.

**Comment by davidlmobley** [comment]
OK, so I'm back online now at least for a bit and will continue where I left off. @JIMonroe - keep in touch when/if you have time to look again.

**Comment by samarjeet** [comment]
I am back as well and will be working on it for a few hours. Are the latest edits on mobley3 branch?

**Comment by davidlmobley** [comment]
Yes, let me push where I am. One sec.

**Comment by davidlmobley** [comment]
OK, I'm done with this, so @samarjeet or @JIMonroe please review and merge when you're OK with it.

@samarjeet - there are a couple small action items for you to deal with, flagged in to-do items. A reference needs to be added, and there's one point I don't  understand that you need to clarify. Please fix (in a separate PR if you like).

I'll likely be offline until early morning beginning shortly (early to bed/early to rise usually). I'll have very limited time in the morning, but I can do quick checks and merge things if needed.

**Comment by samarjeet** [comment]
Yes, it looks good to me. About the comment in step 3 of grid solver, I wanted to convey that the inverse-FFT that we do in step 4 is not just the inverse of what we had on the grid. (Otherwise why would one need to carry out the inverse FFT). There's also a subtle point there that we cannot actually call it the potential energy of the reciprocal-space charge distribution, although it pretty much looks like it.

**Comment by davidlmobley** [comment]
@samarjeet 
> About the comment in step 3 of grid solver, I wanted to convey that the inverse-FFT that we do in step 4 is not just the inverse of what we had on the grid. (Otherwise why would one need to carry out the inverse FFT). 

I still don't understand what you're getting at here. What exactly is changed about the grid?

(Perhaps it's because I haven't implemented this part... But still, I'm probably more educated about this material than our readers will be, so if I don't understand it, it's likely they won't either.)

**Comment by davidlmobley** [comment]
OK,  I'm going to get this merged in and then separately remove or do something to clean up the part referenced above which is still unclear.

**Pull request merged**
