### PR TITLE
Adding my sections and also reformat checklist

### PR DESCRIPTION
**Pull request by davidlmobley**
~This is a work in progress PR in which I begin adding my assigned pieces. Progress~
Here I have added my assigned pieces:

- [x] Switch to new checklist format and clean up checklist
- [x] Write part of classical electrostatics
- [x] Write rest of classical electrostatics
- [x] Write on intermolecular interactions
- [x] Removed extraneous stuff from bottom of checklist

~@JIMonroe @avisekdas -- someone added a couple items at the bottom of the checklist which were not complete thoughts, so I've commented them out here. Can you clarify what you were thinking (if these were yours) so I can address them? The specific items were:~
- ~Ergodicity issue with non-chained Nose-Hoover~
- ~Error that is propagated with integrators in terms of dt~ 
(resolved)

Also cleaned up some formatting issues and enabled comments.

### CODE REVIEW

**Comment by JIMonroe** [comment]
If I added these, I'm not sure what I was talking about. From the sound of both of these, it seems like they are topics to discuss in the "Thermostats" section and the "Integrators" section, respectively. Maybe we can just direct the reader to those sections, mentioning that selection of thermostats and integrators technically impacts the ensemble simulated and system dynamics and thus requires careful consideration?

**Comment by davidlmobley** [comment]
I didn't notice them in your changelog; possibly they were added by someone else before Avisek propagated the Google Doc over here, which seems more likely now that I think about it more.

**Comment by avisekdas** [comment]
Sorry for the delay in responding to your comments. I am not sure who added those two points, we can discuss them elsewhere.

**Comment by davidlmobley** [comment]
Updated with:
- Finished skeletal draft of classical electrostatics bit
- Typo fixes
- Added "to do" list with things I am noticing as I go

**Comment by davidlmobley** [comment]
@JIMonroe @avisekdas - I've added my assigned pieces. Can one of you do a quick check to make sure it looks reasonable to you and then merge? 

(I like the "second pair of eyes looks at it first" model for merging in papers...)

I can bring in references, etc. in a separate PR, once people have a time to look at this and see if it looks reasonable/provide suggestions.

**Comment by JIMonroe** [comment]
Looks great!  I have some minor suggestions for the non-bonded interactions section, but I'll put those comments elsewhere.

I'll go ahead and approve this.

**Pull request merged**
