### PR TITLE
Changed Hoover thermostat to Gaussian

### PR DESCRIPTION
**Pull request by justinGilmer**
Hoover thermostat name can lead to confusion. Changed to its more general name "Gaussian" which better describes how the thermostat algorithm operates.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Thanks!

Conflicting PDF; can you resolve?

**Comment by davidlmobley** [comment]
Ah. That was fast.

**Comment by justinGilmer** [comment]
yeah I realized I had not handled that yet.

I dont think I recompiled the whole document, however.

**Comment by davidlmobley** [comment]
That's OK.

**Pull request merged**
